#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
import numpy as np
arr1 = np.identity(3) # identity는 2차원 nxn 정방단위행렬 
print(arr1)

arr2 = np.eye(3)      # eye는 k 라는 parameter로 대각선을 이동시킬 수 있음 
print(arr2)

arr3 = np.eye(3,3, k=1)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
arr =  np.random.random((3,3,3))
print(arr)

[[[0.97658192 0.73363258 0.4600855 ]
  [0.75506762 0.04128125 0.86536826]
  [0.88144915 0.7092593  0.66310387]]

 [[0.66224195 0.43389122 0.00793472]
  [0.87026916 0.6596345  0.75829204]
  [0.14149405 0.1881026  0.04288206]]

 [[0.95657398 0.43666999 0.77358007]
  [0.97730759 0.42467371 0.00395854]
  [0.39947118 0.9168025  0.41482953]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
np.random.seed(0)
arr = np.random.random((10, 10))
M = arr.max()
m = arr.min()

print(f'최댓값은 {M}, 최솟값은 {m}')

최댓값은 0.9883738380592262, 최솟값은 0.004695476192547066


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
arr = np.random.random((30,))
print(f'arr의 평균값은 {arr.mean()}')

arr의 평균값은 0.46832856746340823


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [76]:
# 방법 1. zeros with fancy indexing
arr1 = np.zeros((5,7))
arr1[[0, arr1.shape[0]-1],:] = 1
arr1[:,[0, arr1.shape[1]-1]] = 1
print(arr1)
print()

# 방법 2. ones with fancy indexing
arr2 = np.ones((5,7))
arr2[1:-1, 1:-1] = 0
print(arr2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [83]:
arr = np.ones((3,4))
print(arr)
print()

pad_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(pad_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [91]:
print(f'0*np.nan는 {0*np.nan}이다.')
print(f'np.nan == np.nan 는 {np.nan==np.nan}이다.')
print(f'np.inf > np.nan 은 {np.inf > np.nan}이다.')
print(f'np.nan - np.nan = {np.nan - np.nan}이다.')
print(f'np.nan in set([np.nan])은 {np.nan in set([np.nan])}이다.')
print(f'0.3 == 3* 0.1은 {0.3==3*0.1}이다.')

0*np.nan는 nan이다.
np.nan == np.nan 는 False이다.
np.inf > np.nan 은 False이다.
np.nan - np.nan = nan이다.
np.nan in set([np.nan])은 True이다.
0.3 == 3* 0.1은 False이다.


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [95]:
arr = np.diag([1, 2, 3, 4],k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [105]:
arr = np.zeros((8,8))
print(arr)
print()
arr[0::2,0::2] = 1
arr[1::2,1::2] = 1

print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
    unravel_index(indices, shape, order='C')

    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.


In [113]:
arr = np.unravel_index(99, (6,7,8))
print(arr)

(1, 5, 3)
